<?php
namespace Heartsentwined\Geoname\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AltName
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AltName extends EntityRepository
{
}
