<?php
namespace Heartsentwined\Geoname\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Locale
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Locale extends EntityRepository
{
}
