<?php
// Auto-generated by Phing, using ZF2's classmap generator
// Generation time: Mon, 17 Sep 2012 16:52:53 +0800
return array(
    'Geoname\Service\Geoname'     => __DIR__ . '/../Geoname/Service/Geoname.php',
    'Geoname\Entity\Place'        => __DIR__ . '/../Geoname/Entity/Place.php',
    'Geoname\Entity\Feature'      => __DIR__ . '/../Geoname/Entity/Feature.php',
    'Geoname\Entity\Timezone'     => __DIR__ . '/../Geoname/Entity/Timezone.php',
    'Geoname\Entity\Meta'         => __DIR__ . '/../Geoname/Entity/Meta.php',
    'Geoname\Entity\Currency'     => __DIR__ . '/../Geoname/Entity/Currency.php',
    'Geoname\Entity\AltName'      => __DIR__ . '/../Geoname/Entity/AltName.php',
    'Geoname\Entity\Language'     => __DIR__ . '/../Geoname/Entity/Language.php',
    'Geoname\Entity\Country'      => __DIR__ . '/../Geoname/Entity/Country.php',
    'Geoname\Entity\Locale'       => __DIR__ . '/../Geoname/Entity/Locale.php',
    'Geoname\Module'              => __DIR__ . '/../Geoname/Module.php',
    'Geoname\Repository\Place'    => __DIR__ . '/../Geoname/Repository/Place.php',
    'Geoname\Repository\Feature'  => __DIR__ . '/../Geoname/Repository/Feature.php',
    'Geoname\Repository\Timezone' => __DIR__ . '/../Geoname/Repository/Timezone.php',
    'Geoname\Repository\Meta'     => __DIR__ . '/../Geoname/Repository/Meta.php',
    'Geoname\Repository\Currency' => __DIR__ . '/../Geoname/Repository/Currency.php',
    'Geoname\Repository\AltName'  => __DIR__ . '/../Geoname/Repository/AltName.php',
    'Geoname\Repository\Language' => __DIR__ . '/../Geoname/Repository/Language.php',
    'Geoname\Repository\Country'  => __DIR__ . '/../Geoname/Repository/Country.php',
    'Geoname\Repository\Locale'   => __DIR__ . '/../Geoname/Repository/Locale.php',
);