<?php
namespace Yalesov\Geoname\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Timezone
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Timezone extends EntityRepository
{
}
